"""add appointment_date v2

Revision ID: 14b8702aa44d
Revises: 5fd3163a7ce6
Create Date: 2026-09-02 16:11:09.846081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b8702aa44d'
down_revision: Union[str, Sequence[str], None] = '5fd3163a7ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_orders', sa.Column('appointment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_orders', 'appointment_date')
    # ### end Alembic commands ###
