"""empty message

Revision ID: 3152bff402f1
Revises: ed22dcd5a8a1
Create Date: 2026-09-07 08:57:59.722284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3152bff402f1'
down_revision: Union[str, Sequence[str], None] = 'ed22dcd5a8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vin_photo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('vin_photo_path')
        batch_op.drop_column('car_photo_path')

    # ### end Alembic commands ###
