"""empty message

Revision ID: 504304f5517c
Revises: cf9292756b78
Create Date: 2026-09-12 13:40:48.399128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504304f5517c'
down_revision: Union[str, Sequence[str], None] = 'cf9292756b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_items', schema=None) as batch_op:
        batch_op.drop_column('claim_status')

    # ### end Alembic commands ###
