"""empty message

Revision ID: a79ac09b8939
Revises: 400140285f26
Create Date: 2026-09-16 11:46:09.228669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79ac09b8939'
down_revision: Union[str, Sequence[str], None] = '400140285f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_items', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
