"""empty message

Revision ID: cf9292756b78
Revises: 3152bff402f1
Create Date: 2026-09-07 13:22:34.999330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9292756b78'
down_revision: Union[str, Sequence[str], None] = '3152bff402f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_models', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
