"""add job card number

Revision ID: e0621530d8fe
Revises: a69720c1fde9
Create Date: 2026-09-05 15:59:06.639837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0621530d8fe'
down_revision: Union[str, Sequence[str], None] = 'a69720c1fde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_card_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('job_card_number')

    # ### end Alembic commands ###
