"""empty message

Revision ID: e9d41594e738
Revises: a79ac09b8939
Create Date: 2026-09-23 12:38:14.929118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d41594e738'
down_revision: Union[str, Sequence[str], None] = 'a79ac09b8939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacted_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contacted_parts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contacted_appointment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contacted_claim', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('contacted_claim')
        batch_op.drop_column('contacted_appointment')
        batch_op.drop_column('contacted_parts')
        batch_op.drop_column('contacted_ready')

    # ### end Alembic commands ###
