"""empty message

Revision ID: ed22dcd5a8a1
Revises: e0621530d8fe
Create Date: 2026-09-07 08:27:38.514675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed22dcd5a8a1'
down_revision: Union[str, Sequence[str], None] = 'e0621530d8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
